from MyPackage.datetime_module import DatetimeTimeMenu
from MyPackage.math_module import MathematicalMenu
from MyPackage.random_module import RandomDataGeneration
from MyPackage.uuid_module import UUID_Module
from MyPackage.file_module import FileMenu
from MyPackage.module_explorer import ExploreModuleMenu